# Generated by Django 3.0.8 on 2020-08-03 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 3, 5, 21, 45, 523136, tzinfo=utc))),
            ],
        ),
    ]
